### ISSUE TITLE
Intallation instructions

### ISSUE THREAD

**Issue by breyten** [open-contracting-partnership/challenge.open-contracting.org#1]
Installation instructions ask you to mirror a website, then running a python http server, but I can't seen to find any python files (I tried the instructions, but it doesn't work unfortunately), and the repo shows at least traces of a Wordpress installation. I'm confused. How do I run this thing?

**Comment by jpmckinney** [comment]
Hi @breyten, there is nothing to run here. The instructions are just to document how we created a backup of the old WordPress site as a static site.

**Comment by jpmckinney** [comment]
If you are looking for a reusable WordPress site, this repository will not be of much use (besides copying some of the HTML and CSS perhaps).

**Comment by breyten** [comment]
Ah, check. Thanks for clarifying!
